"""第一章：最差劲的勇者"""
from .common import Scene, Choice, register

SCENES = [
    Scene(
        id="prologue_01",
        chapter=1,
        location="阿斯托利亚·小酒馆",
        text=(
            "清晨的阳光透过破旧的窗帘照进来。\n"
            "雷克斯从一堆空酒瓶中醒来，头痛欲裂。\n"
            "更糟糕的是——三个愤怒的女人正站在床前，手里拿着各种钝器。\n\n"
            "「你昨晚说要跟我私奔的！」\n"
            "「不对，他跟我说的！」\n"
            "「他跟我说我是他见过最美的女人！」\n\n"
            "雷克斯以惊人的速度翻窗而出，身后传来锅碗瓢盆砸碎的声音。"
        ),
        next_scene="prologue_02",
    ),
    Scene(
        id="prologue_02",
        chapter=1,
        location="酒馆·后门",
        speaker="elena",
        text=(
            "你又来了？昨晚那三个姑娘可是我的常客，你知不知道你给我添了多少麻烦？\n\n"
            "……算了，先进来吃早饭吧。锅里给你热着粥呢。\n"
            "不准从我这里逃跑，公会长巴尔德找你，说是很急的事。"
        ),
        next_scene="prologue_03",
    ),
    Scene(
        id="prologue_03",
        chapter=1,
        location="酒馆·后门",
        speaker="rex",
        text=(
            "公会长大叔找我？肯定是因为我无与伦比的魅力被选为救世勇者了吧！\n\n"
            "……还是说昨天跟那个女骑士搭讪的事被告了？\n"
            "不对，前天跟那个女法师搭讪的事？\n"
            "大前天跟那个女弓箭手……\n\n"
            "算了，去了就知道了。艾莲娜，你的粥还是一样好喝！"
        ),
        next_scene="ch1_guild_01",
    ),
    Scene(
        id="ch1_guild_01",
        chapter=1,
        location="冒险者公会",
        speaker="guild_master",
        text=(
            "雷克斯！你这个混蛋！这已经是你被踢出的第七个队伍了！\n"
            "第——七——个！\n\n"
            "上一个队伍的女骑士投诉说你在战斗中盯着她铠甲的缝隙看！"
        ),
        next_scene="ch1_guild_02",
    ),
    Scene(
        id="ch1_guild_02",
        chapter=1,
        location="冒险者公会",
        speaker="rex",
        text=(
            "冤枉啊公会长大叔！我只是想帮她检查一下防护是否完整！\n"
            "作为一个有责任心的队友，关心同伴的装备状况不是很正常的事吗？\n\n"
            "……好吧，确实看了。但是说实话那个缝隙确实需要修补——"
        ),
        next_scene="ch1_guild_03",
    ),
    Scene(
        id="ch1_guild_03",
        chapter=1,
        location="冒险者公会",
        speaker="guild_master",
        text=(
            "闭嘴！听好了，这是你最后的机会。\n\n"
            "低语之森最近出现了异常的黑暗能量波动，需要人去调查。\n"
            "这个任务很危险，但如果你能完成……我可以不把你永久除名。\n\n"
            "如果你再搞砸，或者再骚扰队友——你就永远别想踏进任何公会的大门。"
        ),
        choices=[
            Choice(
                text="为了世界和平！（顺便看看森林里有没有漂亮的精灵）",
                next_scene="ch1_meet_sera_01",
                affection={"elena": -1},
            ),
            Choice(
                text="好吧好吧，看在公会长大叔你那闪闪发光的秃头的面子上",
                next_scene="ch1_meet_sera_01",
            ),
            Choice(
                text="只要队伍里有美女就行！这是我唯一的条件！",
                next_scene="ch1_meet_sera_01",
                flags=["honest_pervert"],
            ),
        ],
    ),
    Scene(
        id="ch1_meet_sera_01",
        chapter=1,
        location="冒险者公会",
        text=(
            "话音刚落，公会大门被一脚踢开。\n\n"
            "金色的长发在阳光中飞扬，银白色的圣骑士铠甲闪耀着神圣的光芒。\n"
            "一个英姿飒爽的女骑士大步走入，目光如剑。\n\n"
            "整个公会瞬间安静下来。"
        ),
        next_scene="ch1_meet_sera_02",
    ),
    Scene(
        id="ch1_meet_sera_02",
        chapter=1,
        location="冒险者公会",
        speaker="seraphina",
        text=(
            "我是圣骑士团副团长赛拉菲娜。\n"
            "奉命监视——我是说，协助一位叫雷克斯的冒险者执行任务。\n\n"
            "……哪个是雷克斯？"
        ),
        next_scene="ch1_meet_sera_03",
    ),
    Scene(
        id="ch1_meet_sera_03",
        chapter=1,
        location="冒险者公会",
        speaker="rex",
        text=(
            "哦？金色长发，蓝色眼睛，还穿着紧身铠甲……\n"
            "这一定是命运的安排吧？公会长大叔，你终于做了一件好事！"
        ),
        choices=[
            Choice(
                text="（认真地鞠躬）抱歉之前的失礼。我是雷克斯，请多多关照。",
                next_scene="ch1_prep_01",
                affection={"seraphina": 3},
            ),
            Choice(
                text="割舌头？那我就不能用嘴做很多有趣的事了哦~比如说……吃饭什么的。",
                next_scene="ch1_prep_01",
                affection={"seraphina": -2},
                flags=["extreme_flirt"],
            ),
            Choice(
                text="（心想：好可怕……但是好帅啊。这种反差感太犯规了。）",
                next_scene="ch1_prep_01",
                affection={"seraphina": 1},
            ),
        ],
    ),
    Scene(
        id="ch1_prep_01",
        chapter=1,
        location="冒险者公会",
        speaker="seraphina",
        text=(
            "……原来你就是那个臭名昭著的色鬼冒险者。\n"
            "听好了，我奉命监视你。如果你敢有任何——任何——不轨的举动，\n"
            "我的剑可比你的嘴快得多。\n\n"
            "明天一早出发，去准备你的装备。"
        ),
        next_scene="ch1_elena_01",
    ),
    Scene(
        id="ch1_elena_01",
        chapter=1,
        location="艾莲娜的酒馆·二楼",
        text=(
            "雷克斯回到艾莲娜的酒馆收拾行李。\n"
            "艾莲娜倚在门框上，看着他把东西胡乱塞进背包。\n"
            "她的眼神里有担忧，有不舍，还有一些说不清的东西。"
        ),
        next_scene="ch1_elena_02",
    ),
    Scene(
        id="ch1_elena_02",
        chapter=1,
        location="艾莲娜的酒馆·二楼",
        speaker="elena",
        text=(
            "给你，这个带上。\n\n"
            "（她递过来一个手工编织的护身符，针脚细密而用心。）\n\n"
            "你总是这样……把所有人推开，用那些轻浮的话。\n"
            "明明实力很强，却总是在搞砸。你到底……在逃避什么？"
        ),
        choices=[
            Choice(
                text="艾莲娜……我一定会回来的。这次是认真的。",
                next_scene="ch1_depart_01",
                affection={"elena": 5},
                flags=["elena_promise"],
            ),
            Choice(
                text="别担心啦，我可是被七个队伍踢出来都没死的男人！",
                next_scene="ch1_depart_01",
                affection={"elena": 2},
            ),
            Choice(
                text="你这么担心我，难道是喜欢我？（坏笑）",
                next_scene="ch1_elena_03",
                affection={"elena": 1},
            ),
        ],
    ),
    Scene(
        id="ch1_elena_03",
        chapter=1,
        location="艾莲娜的酒馆·二楼",
        speaker="elena",
        text=(
            "你、你在说什么呢！谁会喜欢你这种人啊！\n\n"
            "（脸涨得通红，一脚把雷克斯踢出了房间。）\n\n"
            "笨蛋！大笨蛋！快给我滚去准备行李！\n\n"
            "（门关上后，她背靠着门，轻轻地摸了摸自己发烫的脸颊。）"
        ),
        next_scene="ch1_depart_01",
    ),
    Scene(
        id="ch1_depart_01",
        chapter=1,
        location="阿斯托利亚·城门口",
        text=(
            "第二天清晨，雷克斯和赛拉菲娜在城门口会合。\n\n"
            "晨雾中，赛拉菲娜已经在那里等了很久。\n"
            "她的表情依然冷淡，但雷克斯第一次注意到——\n"
            "那双蓝色的眼睛里，不只有冷漠，还藏着一丝说不清的悲伤。"
        ),
        next_scene="ch1_road_01",
    ),
    Scene(
        id="ch1_road_01",
        chapter=1,
        location="通往低语之森的大道",
        speaker="rex",
        text=(
            "赛拉菲娜小姐——\n"
            "不对，赛拉菲娜大人？\n"
            "还是叫小赛？阿菲？菲菲？\n\n"
            "……你看，你不说话我会一直尝试新的称呼的哦？"
        ),
        next_scene="ch1_road_02",
    ),
    Scene(
        id="ch1_road_02",
        chapter=1,
        location="通往低语之森的大道",
        speaker="seraphina",
        text="叫我的名字就好。别加奇怪的后缀。",
        next_scene="ch1_battle_01",
    ),
    Scene(
        id="ch1_battle_01",
        chapter=1,
        location="通往低语之森的大道",
        text=(
            "前方的树林边缘传来喊叫声。\n\n"
            "一群山贼围住了一辆商人的马车。\n"
            "一个小女孩躲在父亲身后，吓得浑身发抖。\n\n"
            "赛拉菲娜已经拔出了剑。"
        ),
        choices=[
            Choice(
                text="我来引开注意力，你从侧面包抄。配合作战！",
                next_scene="ch1_battle_02",
                affection={"seraphina": 2},
                flags=["tactical_rex"],
            ),
            Choice(
                text="美女骑士，展示你的英姿吧！我在后面……欣赏，呃，支援！",
                next_scene="ch1_battle_02",
                affection={"seraphina": -1},
            ),
            Choice(
                text="（不说话，直接冲上去挡在那家人面前）",
                next_scene="ch1_battle_02",
                affection={"seraphina": 4},
                flags=["heroic_rex"],
            ),
        ],
    ),
    Scene(
        id="ch1_battle_02",
        chapter=1,
        location="通往低语之森的大道",
        text=(
            "战斗很快结束了。雷克斯的实力远超预期——\n"
            "即便是赛拉菲娜也不得不承认，这个色鬼确实有两把刷子。\n\n"
            "那个小女孩跑过来，抱住了雷克斯的腿。\n"
            "「谢谢你，大哥哥！」\n\n"
            "雷克斯蹲下来，温柔地摸了摸她的头。\n"
            "「没事了哦。坏人都被打跑了。」\n\n"
            "赛拉菲娜看着这一幕，眼神微微变化。"
        ),
        next_scene="ch1_camp_01",
    ),
    Scene(
        id="ch1_camp_01",
        chapter=1,
        location="营地·篝火旁",
        text=(
            "夜幕降临，他们在路边扎营。\n\n"
            "篝火噼啪作响，映照出两个沉默的身影。\n"
            "赛拉菲娜难得地没有板着脸，火光让她的表情看起来柔和了一些。"
        ),
        next_scene="ch1_camp_02",
    ),
    Scene(
        id="ch1_camp_02",
        chapter=1,
        location="营地·篝火旁",
        speaker="seraphina",
        text=(
            "……你今天的表现，出乎我的意料。\n\n"
            "我以前有个弟弟，也是个不靠谱的笨蛋。\n"
            "但是在关键时刻……总是第一个冲上去的人。"
        ),
        choices=[
            Choice(
                text="他现在在哪里？",
                next_scene="ch1_camp_03",
                affection={"seraphina": 2},
            ),
            Choice(
                text="（不说话，安静地给她递了一杯热茶。）",
                next_scene="ch1_camp_03",
                affection={"seraphina": 3},
                flags=["rex_gentle_moment"],
            ),
            Choice(
                text="看来你对不靠谱的笨蛋有特殊的感情嘛~",
                next_scene="ch1_camp_03",
                affection={"seraphina": 1},
            ),
        ],
    ),
    Scene(
        id="ch1_camp_03",
        chapter=1,
        location="营地·篝火旁",
        speaker="seraphina",
        text=(
            "……他不在了。\n\n"
            "（她低下头，火光在她的金发上跳动。）\n\n"
            "……算了，不说这个了。早点休息，明天就到低语之森了。"
        ),
        next_scene="ch1_end",
    ),
    Scene(
        id="ch1_end",
        chapter=1,
        location="营地·篝火旁",
        text=(
            "赛拉菲娜裹着斗篷躺下了。\n"
            "雷克斯独自望着星空，篝火渐渐暗淡。\n\n"
            "很久很久，他轻声说了一句：\n"
            "「妈妈……我又要去森林了。」\n\n"
            "赛拉菲娜的眼睛微微张开，看着雷克斯的背影。\n"
            "她的嘴唇动了动，最终什么也没说。\n\n"
            "远处，低语之森在月光下沉默地等待着。"
        ),
        next_scene="ch2_forest_01",
    ),
]

register(*SCENES)
