"""第三章：圣城祭典"""
from .common import Scene, Choice, register

SCENES = [
    Scene(
        id="ch3_city_01",
        chapter=3,
        location="圣城·塞莱斯蒂亚",
        text=(
            "圣城塞莱斯蒂亚。\n\n"
            "洁白的大理石建筑在阳光下熠熠生辉，\n"
            "街道两旁挂满了七彩的灯笼和花环——光之祭典即将开始。\n\n"
            "穿着节日盛装的人们川流不息，笑声和音乐交织在一起。"
        ),
        next_scene="ch3_city_02",
    ),
    Scene(
        id="ch3_city_02",
        chapter=3,
        location="圣城·塞莱斯蒂亚",
        speaker="rex",
        text=(
            "圣城啊……！听说这里的修女们都穿着白色长袍，\n"
            "在月光下祈祷的样子简直就像是天使降临——\n"
            "而且祭典期间大家都穿着轻薄的夏装，这简直是——"
        ),
        next_scene="ch3_city_03",
    ),
    Scene(
        id="ch3_city_03",
        chapter=3,
        location="圣城·塞莱斯蒂亚",
        speaker="seraphina",
        text="闭嘴。我们是来执行任务的，不是来度假的。",
        next_scene="ch3_city_04",
    ),
    Scene(
        id="ch3_city_04",
        chapter=3,
        location="圣城·塞莱斯蒂亚",
        speaker="luna",
        text=(
            "……他说的话有什么问题吗？\n"
            "天使降临……是宗教用语吗？\n"
            "轻薄的夏装……确实很合理，现在气温很高。\n\n"
            "（完全没有理解言外之意地歪着头。）"
        ),
        next_scene="ch3_city_05",
    ),
    Scene(
        id="ch3_city_05",
        chapter=3,
        location="圣城·塞莱斯蒂亚",
        speaker="rex",
        text=(
            "看吧赛拉菲娜，露娜都觉得我说得很有道理！\n"
            "纯洁的精灵小姐认证了我的清白！"
        ),
        next_scene="ch3_city_06",
    ),
    Scene(
        id="ch3_city_06",
        chapter=3,
        location="圣城·塞莱斯蒂亚",
        speaker="seraphina",
        text=(
            "……你利用别人的天真来给自己开脱，这让我更想揍你了。\n\n"
            "走吧，先去光之大神殿报到。"
        ),
        next_scene="ch3_mira_01",
    ),
    Scene(
        id="ch3_mira_01",
        chapter=3,
        location="光之大神殿",
        text=(
            "光之大神殿。\n"
            "巨大的彩色玻璃窗洒下斑斓的光芒，\n"
            "空气中弥漫着淡淡的薰香味道。\n\n"
            "一个身穿白色祭司服的少女蹦蹦跳跳地迎了上来，\n"
            "绿色的短发在阳光下闪亮，笑容灿烂得像向日葵。"
        ),
        next_scene="ch3_mira_02",
    ),
    Scene(
        id="ch3_mira_02",
        chapter=3,
        location="光之大神殿",
        speaker="mira",
        text=(
            "你们好你们好！我是见习牧师米拉！\n"
            "是负责接待你们的联络员！请多多指教！\n\n"
            "啊！你就是那个传说中被七个队伍踢出来的色鬼勇者吧？！\n"
            "哇，久仰大名久仰大名！真人比传说中帅嘛~"
        ),
        next_scene="ch3_mira_03",
    ),
    Scene(
        id="ch3_mira_03",
        chapter=3,
        location="光之大神殿",
        speaker="rex",
        text=(
            "我的名声传到圣城了？！这种感觉是骄傲还是羞耻？！\n"
            "算了不重要——米拉小姐，你笑起来真可爱，\n"
            "有没有兴趣和我共进晚餐？我知道一个——"
        ),
        next_scene="ch3_mira_04",
    ),
    Scene(
        id="ch3_mira_04",
        chapter=3,
        location="光之大神殿",
        speaker="mira",
        text=(
            "好呀好呀！不过你要请客哦~\n\n"
            "（她眨眨眼睛，嘴角的笑容里藏着一丝狡黠。）\n\n"
            "说起来，赛拉菲娜副团长的脸色好可怕呀~\n"
            "还有这位精灵小姐抓着你袖子的力度好像变大了呢~\n"
            "你可真受欢迎！"
        ),
        next_scene="ch3_mira_05",
    ),
    Scene(
        id="ch3_mira_05",
        chapter=3,
        location="光之大神殿",
        speaker="mira",
        text=(
            "好了好了，说正事~\n\n"
            "最近圣城地下的古代封印出现了异常波动。\n"
            "黑暗能量的读数在夜间会急剧上升，我们怀疑有人在暗中破坏封印。\n"
            "趁祭典期间人多眼杂，正好展开调查~\n\n"
            "（她看了露娜一眼，目光在露娜身上停留了一瞬，\n"
            "但什么也没说。）"
        ),
        next_scene="ch3_festival_01",
    ),
    Scene(
        id="ch3_festival_01",
        chapter=3,
        location="圣城·祭典大街",
        text=(
            "调查要等到晚上才能开始。\n"
            "在那之前——难得的祭典，不好好逛逛可说不过去。\n\n"
            "街上满是小吃摊、游戏摊、杂耍表演。\n"
            "三个女孩子都用各自的方式表现出了兴趣——\n"
            "赛拉菲娜假装不在意但一直看向小吃摊，\n"
            "露娜面无表情但眼睛一直追着一个发光的风车，\n"
            "米拉早就买了一串糖葫芦在啃了。"
        ),
        choices=[
            Choice(
                text="赛拉菲娜，一起去逛逛吧！我请你吃烤肉串！",
                next_scene="ch3_festival_02",
                affection={"seraphina": 2},
            ),
            Choice(
                text="露娜，你见过祭典吗？我带你到处看看！",
                next_scene="ch3_festival_02",
                affection={"luna": 3},
            ),
            Choice(
                text="米拉，你这个圣城通，当导游怎么样？",
                next_scene="ch3_festival_02",
                affection={"mira": 2},
            ),
        ],
    ),
    Scene(
        id="ch3_festival_02",
        chapter=3,
        location="圣城·祭典大街",
        text=(
            "祭典的热闹气氛感染了所有人。\n\n"
            "雷克斯在射击摊前连中了十发，老板脸都绿了。\n"
            "赛拉菲娜在力量测试中一锤把测量仪打爆了。\n"
            "露娜盯着占卜摊看了半小时，占卜师自己先慌了。\n"
            "米拉把沿路所有小吃都尝了个遍。\n\n"
            "雷克斯虽然时不时看路过的美女，但每次都被三个方向的目光钉在原地。"
        ),
        next_scene="ch3_festival_03",
    ),
    Scene(
        id="ch3_festival_03",
        chapter=3,
        location="圣城·祭典大街",
        text=(
            "雷克斯在一个游戏摊前赢得了一个毛绒玩偶——\n"
            "一只胖乎乎的白色小猫，做工还挺精致的。\n\n"
            "三双眼睛同时看向了那只玩偶。\n"
            "空气中弥漫着微妙的紧张感。"
        ),
        choices=[
            Choice(
                text="送给赛拉菲娜——你生气的时候可以捏它出气，别老是捏我。",
                next_scene="ch3_festival_04",
                affection={"seraphina": 3},
            ),
            Choice(
                text="送给露娜——你好像从来没有过属于自己的东西。",
                next_scene="ch3_festival_04",
                affection={"luna": 4},
            ),
            Choice(
                text="送给米拉——谢谢你的招待，小导游~",
                next_scene="ch3_festival_04",
                affection={"mira": 3},
            ),
        ],
    ),
    Scene(
        id="ch3_festival_04",
        chapter=3,
        location="圣城·祭典大街",
        text=(
            "收到玩偶的人露出了意想不到的表情——\n"
            "不管是谁，都在那一刻展现出了最真实的一面。\n\n"
            "没有收到的人虽然表面若无其事，\n"
            "但眼神里闪过了一丝失落。\n\n"
            "雷克斯看到了，心想：\n"
            "「糟糕……下次要买三个才行。不对，如果加上艾莲娜的话要四个……」"
        ),
        next_scene="ch3_dark_01",
    ),
    Scene(
        id="ch3_dark_01",
        chapter=3,
        location="光之大神殿·地下回廊",
        text=(
            "夜幕降临，祭典的灯火在远处闪耀。\n\n"
            "四人进入了神殿的地下回廊。\n"
            "古老的石壁上刻满了密密麻麻的封印符文，\n"
            "但其中有些符文已经暗淡——甚至出现了裂纹。"
        ),
        next_scene="ch3_dark_02",
    ),
    Scene(
        id="ch3_dark_02",
        chapter=3,
        location="光之大神殿·地下回廊",
        speaker="mira",
        text=(
            "这些封印是一千年前的大贤者留下的。\n"
            "据说下面封着某种……非常危险的东西。\n"
            "但具体是什么，连大祭司也不完全清楚。\n\n"
            "最近这些裂纹在加速扩大……好像有什么力量在从外部侵蚀它们。"
        ),
        next_scene="ch3_dark_03",
    ),
    Scene(
        id="ch3_dark_03",
        chapter=3,
        location="光之大神殿·地下回廊",
        text=(
            "露娜又开始头痛了。\n"
            "她认出了那些符文——虽然她不知道为什么自己会认识。\n\n"
            "米拉在一旁仔细地观察着露娜的反应，\n"
            "然后轻轻拉了拉雷克斯的袖子，示意他到一边说话。"
        ),
        next_scene="ch3_dark_04",
    ),
    Scene(
        id="ch3_dark_04",
        chapter=3,
        location="光之大神殿·地下回廊",
        speaker="mira",
        text=(
            "（小声）那个精灵小姐……她不是普通人，对吧？\n\n"
            "她的灵魂颜色很特殊——我从来没见过那样的颜色。\n"
            "像是……被染上了千年岁月的古老银色。\n\n"
            "普通精灵活不了那么久的。"
        ),
        choices=[
            Choice(
                text="你看出来了？……我也不确定她到底是谁。但我相信她不是敌人。",
                next_scene="ch3_mira_reveal_01",
                affection={"mira": 3},
                flags=["mira_trust"],
            ),
            Choice(
                text="你在说什么？她只是失忆了而已~你想太多了吧，小牧师？",
                next_scene="ch3_mira_reveal_01",
                affection={"mira": -1},
            ),
            Choice(
                text="就算她有什么秘密……我也会保护她的。不管她是谁。",
                next_scene="ch3_mira_reveal_01",
                affection={"mira": 2, "luna": 1},
            ),
        ],
    ),
    Scene(
        id="ch3_mira_reveal_01",
        chapter=3,
        location="神殿·花园",
        speaker="mira",
        text=(
            "调查结束后，米拉带雷克斯来到神殿的花园。\n"
            "月光下的白色花朵散发着淡淡的荧光。\n\n"
            "她的表情少见地变得认真起来。\n\n"
            "我跟你说个秘密哦——我有一种特殊能力，能看到人的「灵魂之色」。\n"
            "你的灵魂啊……像太阳一样，外面是灿烂的金色。\n\n"
            "但是中心有一块……很深很深的黑暗。"
        ),
        next_scene="ch3_mira_reveal_02",
    ),
    Scene(
        id="ch3_mira_reveal_02",
        chapter=3,
        location="神殿·花园",
        speaker="mira",
        text=(
            "你在用笑容和轻浮掩盖什么，对吧？\n\n"
            "那些搭讪，那些没正经的话——都是你的盾牌。\n"
            "把别人逗笑，把别人推远，这样就没人能靠近那个黑暗——\n\n"
            "十年前……你失去了什么？"
        ),
        choices=[
            Choice(
                text="（沉默了很久很久）……你看到的太多了，小牧师。有些东西，看到了就再也收不回去了。",
                next_scene="ch3_mira_reveal_03",
                affection={"mira": 4},
                flags=["mira_saw_truth"],
            ),
            Choice(
                text="哈哈~你说什么呢？我的灵魂里只有对美女无尽的爱而已~",
                next_scene="ch3_mira_reveal_03",
                affection={"mira": 1},
            ),
            Choice(
                text="（转身离开，不回头。月光把他的影子拉得很长。）",
                next_scene="ch3_mira_reveal_03",
                flags=["rex_avoids_truth"],
            ),
        ],
    ),
    Scene(
        id="ch3_mira_reveal_03",
        chapter=3,
        location="神殿·花园",
        speaker="mira",
        text=(
            "（她看着雷克斯的背影，轻声说：）\n\n"
            "没关系的……你不想说就不用说。\n"
            "但是你要知道——你不用一个人扛着。\n\n"
            "（她双手合十，低声祈祷。）\n\n"
            "神啊，请保佑这个嘴巴很坏但心肠很好的笨蛋……"
        ),
        next_scene="ch3_attack_01",
    ),
    Scene(
        id="ch3_attack_01",
        chapter=3,
        location="圣城·祭典广场",
        text=(
            "突然——\n\n"
            "大地震颤，封印符文的裂缝急剧扩大。\n"
            "黑色的雾气从地面涌出，凝聚成扭曲的魔物形态。\n\n"
            "祭典广场上传来尖叫声。人群四散奔逃。\n"
            "魔物——至少有二十多只——向平民扑去。"
        ),
        next_scene="ch3_attack_02",
    ),
    Scene(
        id="ch3_attack_02",
        chapter=3,
        location="圣城·祭典广场",
        text=(
            "雷克斯拔出剑的速度快得惊人——\n"
            "一道金色的剑气划破夜空，将三只魔物同时斩成碎片。\n\n"
            "赛拉菲娜愣住了。这种剑术，这种魔力输出——\n"
            "远远超过一个普通冒险者应有的水平。"
        ),
        next_scene="ch3_attack_03",
    ),
    Scene(
        id="ch3_attack_03",
        chapter=3,
        location="圣城·祭典广场",
        speaker="seraphina",
        text="你……一直在隐藏实力？",
        next_scene="ch3_attack_04",
    ),
    Scene(
        id="ch3_attack_04",
        chapter=3,
        location="圣城·祭典广场",
        speaker="rex",
        text=(
            "嘘——不要告诉别人。\n"
            "不然会有更多美女喜欢上我的，我应付不过来~\n\n"
            "（但他的眼神是认真的——像换了一个人。）\n\n"
            "赛拉菲娜，护住左翼的平民！露娜，用魔力感知引导我们！\n"
            "米拉——"
        ),
        next_scene="ch3_attack_05",
    ),
    Scene(
        id="ch3_attack_05",
        chapter=3,
        location="圣城·祭典广场",
        text=(
            "米拉冲向了一个被魔物逼到角落的小女孩——\n"
            "她张开了防护结界，但魔物的爪子击碎了结界。\n"
            "米拉用身体护住了那个孩子。"
        ),
        choices=[
            Choice(
                text="米拉！！（冲过去治疗她，用自己的身体挡住第二波攻击）",
                next_scene="ch3_aftermath_01",
                affection={"mira": 5},
                flags=["saved_mira"],
            ),
            Choice(
                text="赛拉菲娜，保护米拉！我来解决这些东西！",
                next_scene="ch3_aftermath_01",
                affection={"seraphina": 2, "mira": 2},
            ),
            Choice(
                text="露娜，能用你的力量感知封印的弱点吗？从源头切断！",
                next_scene="ch3_aftermath_01",
                affection={"luna": 2},
            ),
        ],
    ),
    Scene(
        id="ch3_aftermath_01",
        chapter=3,
        location="神殿·疗养室",
        text=(
            "战斗结束了。\n\n"
            "魔物被消灭，平民的伤亡奇迹般地控制在了最小范围。\n"
            "但封印的裂纹更大了。\n\n"
            "米拉躺在疗养室里，伤势不重但需要休息。\n"
            "她看到走进来的雷克斯，虚弱地笑了。"
        ),
        next_scene="ch3_aftermath_02",
    ),
    Scene(
        id="ch3_aftermath_02",
        chapter=3,
        location="神殿·疗养室",
        speaker="mira",
        text=(
            "嘿嘿……谢谢你。\n\n"
            "你果然不像表面看起来那样嘛。\n"
            "色鬼勇者？我看是温柔勇者才对~"
        ),
        next_scene="ch3_aftermath_03",
    ),
    Scene(
        id="ch3_aftermath_03",
        chapter=3,
        location="神殿·疗养室",
        speaker="rex",
        text=(
            "别说出去啊！会影响我花花公子的形象的！\n\n"
            "我这个人吧，只有两个信条——\n"
            "第一，追求天下所有的美女。\n"
            "第二，不让任何美女受伤。\n\n"
            "所以你受伤了是我的失职，别谢我了。\n"
            "赶紧好起来，然后让我好好补偿你~"
        ),
        next_scene="ch3_aftermath_04",
    ),
    Scene(
        id="ch3_aftermath_04",
        chapter=3,
        location="神殿·疗养室",
        speaker="mira",
        text=(
            "（她轻轻地抓住了雷克斯的手。）\n\n"
            "我说啊……你这种人最讨厌了。\n"
            "明明是认真的话，非要用玩笑的方式说出来。\n\n"
            "有一天，你要好好面对自己的心才行啊。\n\n"
            "（握着他的手睡着了，嘴角还挂着微笑。）"
        ),
        next_scene="ch3_end",
    ),
    Scene(
        id="ch3_end",
        chapter=3,
        location="神殿·屋顶",
        text=(
            "深夜。雷克斯独自坐在神殿的屋顶上。\n\n"
            "圣城的夜景在脚下铺展开来，\n"
            "祭典的灯火虽然因为袭击暗淡了许多，但还没有完全熄灭。\n\n"
            "米拉的话在耳边回响——「灵魂中心的黑暗」。\n"
            "他握着艾莲娜做的护身符，指尖无意识地摩挲着。\n\n"
            "楼下，露娜站在窗前看着他的身影。\n"
            "走廊里，赛拉菲娜经过时停下了脚步。\n"
            "疗养室里，米拉在睡梦中低声祈祷。\n\n"
            "四个女人，每个人都开始看到面具背后的东西了。\n\n"
            "一个信使匆匆赶到：\n"
            "「边境急报——一个半魔族少女在荒野中大肆破坏！\n"
            "已有多支讨伐队被击退！」\n\n"
            "雷克斯望向黑暗的地平线，自言自语：\n"
            "「魔族……吗。」\n\n"
            "他的眼睛里映着远方的火光，\n"
            "那种表情，仿佛在看着十年前的某个夜晚。"
        ),
        next_scene="ch4_border_01",
    ),
]

register(*SCENES)
