"""第四章：魔族之女"""
from .common import Scene, Choice, register

SCENES = [
    Scene(
        id="ch4_border_01",
        chapter=4,
        location="魔族边境·荒野",
        text=(
            "魔族边境。\n\n"
            "寸草不生的大地上散布着暗红色的岩石，\n"
            "远方的火山喷出的浓烟将天空染成永恒的灰色。\n"
            "空气中弥漫着硫磺和灰烬的味道。\n\n"
            "雷克斯从进入边境开始就异常沉默。"
        ),
        next_scene="ch4_border_02",
    ),
    Scene(
        id="ch4_border_02",
        chapter=4,
        location="魔族边境·荒野",
        speaker="seraphina",
        text=(
            "你怎么了？从进入边境开始就没说一句调戏人的话。\n"
            "虽然安静了很好……但这不像你。"
        ),
        next_scene="ch4_border_03",
    ),
    Scene(
        id="ch4_border_03",
        chapter=4,
        location="魔族边境·荒野",
        speaker="rex",
        text=(
            "啊？没什么啦~只是在想酒馆里新来的那个女服务——\n"
            "好吧我编不下去了。\n\n"
            "……这片荒野的味道，让我想起一些不太愉快的事情而已。\n"
            "没什么大不了的。"
        ),
        next_scene="ch4_border_04",
    ),
    Scene(
        id="ch4_border_04",
        chapter=4,
        location="魔族边境·荒野",
        speaker="luna",
        text=(
            "……你的魔力波动和进入低语之森时一样不安定。\n\n"
            "你在害怕。不，不是害怕……是愤怒。\n"
            "还有……悲伤。"
        ),
        next_scene="ch4_border_05",
    ),
    Scene(
        id="ch4_border_05",
        chapter=4,
        location="魔族边境·荒野",
        speaker="rex",
        text=(
            "精灵小姐，请不要随便偷看别人的魔力好不好？\n"
            "这种行为跟偷看别人洗澡一样不礼貌的~\n\n"
            "（他笑着说，但眼睛没有在笑。）"
        ),
        next_scene="ch4_village_01",
    ),
    Scene(
        id="ch4_village_01",
        chapter=4,
        location="废墟村庄",
        text=(
            "前方出现了一座废弃的村庄。\n\n"
            "但这些废墟不是魔族造成的——\n"
            "烧焦的痕迹中混杂着人类武器的残骸。\n"
            "是人类军队烧的——因为这个村子住着半人半魔族的混血。\n\n"
            "米拉捂住了嘴。赛拉菲娜的拳头攥紧了。"
        ),
        next_scene="ch4_lilith_01",
    ),
    Scene(
        id="ch4_lilith_01",
        chapter=4,
        location="废墟村庄",
        text=(
            "一道火球从废墟中射出，差点命中队伍！\n\n"
            "碎石飞散中，一个身影跃出——\n"
            "小小的犄角从红色的头发中探出，一条细长的尾巴在身后甩动。\n"
            "猩红色的眼睛充满敌意，双手燃烧着赤红的魔焰。\n\n"
            "一个半魔族少女，大约十六七岁，浑身伤痕。"
        ),
        next_scene="ch4_lilith_02",
    ),
    Scene(
        id="ch4_lilith_02",
        chapter=4,
        location="废墟村庄",
        speaker="lilith",
        text=(
            "又是人类！你们来干什么？！\n"
            "要杀我就放马过来！老娘今天心情很差！\n\n"
            "（她的手在发抖。不是因为愤怒——是因为恐惧和疲惫。\n"
            "身上的伤口还在渗血。她已经连续战斗很久了。）"
        ),
        choices=[
            Choice(
                text="等等等等！我们不是来打架的！虽然你很可爱，犄角和尾巴什么的，新属性太棒了——",
                next_scene="ch4_lilith_03",
                affection={"lilith": -1},
            ),
            Choice(
                text="（挡在队友前面，放下武器）你先冷静。看我的眼睛——我们是来帮忙的。",
                next_scene="ch4_lilith_03",
                affection={"lilith": 2, "seraphina": 1},
            ),
            Choice(
                text="露娜，你能感应到吗？她的魔力……不是攻击性的。她在害怕。",
                next_scene="ch4_lilith_03",
                affection={"lilith": 3, "luna": 1},
                flags=["sensed_lilith_fear"],
            ),
        ],
    ),
    Scene(
        id="ch4_lilith_03",
        chapter=4,
        location="废墟村庄",
        text=(
            "经过一番周旋——其中包括雷克斯被火球烧掉半边袖子、\n"
            "赛拉菲娜三次差点动剑、米拉用治愈魔法帮莉莉丝止血——\n"
            "少女终于放下了敌意。\n\n"
            "只是放下了敌意。戒备心还在。"
        ),
        next_scene="ch4_lilith_04",
    ),
    Scene(
        id="ch4_lilith_04",
        chapter=4,
        location="废墟村庄·地下室",
        speaker="lilith",
        text=(
            "我叫莉莉丝。\n"
            "魔王阿扎泽尔的女儿——不对，前女儿。\n\n"
            "我背叛了他，因为我不相信他发动战争的理由。\n"
            "他说这一切是「为了两个种族的未来」，但我看到的只有死亡和毁灭。\n\n"
            "然后人类这边呢？\n"
            "知道我是魔王的女儿，不管我是来投诚的还是来做什么的——\n"
            "直接就要杀我。\n\n"
            "两边都一样。"
        ),
        next_scene="ch4_lilith_05",
    ),
    Scene(
        id="ch4_lilith_05",
        chapter=4,
        location="废墟村庄·地下室",
        speaker="lilith",
        text=(
            "你们人类都一样的。\n"
            "表面上说和平，说包容，说理解——\n"
            "背后就拿着刀。\n\n"
            "（她缩在角落，用尾巴把自己裹起来。\n"
            "那只尾巴在发抖。）"
        ),
        choices=[
            Choice(
                text="两边都被抛弃的感觉……我懂。（看向窗外的废墟，眼神变得遥远）",
                next_scene="ch4_bond_01",
                affection={"lilith": 5},
                flags=["rex_reveals_past"],
            ),
            Choice(
                text="你不一样。你选择了离开那个地方，这需要比任何人都大的勇气。",
                next_scene="ch4_bond_02",
                affection={"lilith": 3},
            ),
            Choice(
                text="跟我们走吧。至少在我眼里，有犄角有尾巴的女孩子也超有魅力的~",
                next_scene="ch4_bond_02",
                affection={"lilith": 2},
            ),
        ],
    ),
    Scene(
        id="ch4_bond_01",
        chapter=4,
        location="废墟村庄·地下室",
        speaker="rex",
        text=(
            "我曾经有一个家，叫灰谷村。\n\n"
            "十年前——人类的盗贼团和魔族的侦察部队几乎同时盯上了我们。\n"
            "一个要抢，一个要杀。\n"
            "两边打起来了，夹在中间的村子变成了战场。\n\n"
            "我活下来了。\n"
            "趴在妈妈身体下面，听着外面的火焰和惨叫声。\n"
            "整整一夜。\n\n"
            "我那年十岁。"
        ),
        next_scene="ch4_bond_01b",
    ),
    Scene(
        id="ch4_bond_01b",
        chapter=4,
        location="废墟村庄·地下室",
        text=(
            "整个地下室沉默了。\n\n"
            "赛拉菲娜死死地咬着下唇。\n"
            "露娜无声地流下了眼泪——她不知道为什么，只是控制不住。\n"
            "米拉双手合十，低下了头。\n\n"
            "莉莉丝看着雷克斯的眼睛，看到了和自己一样的东西——\n"
            "一个被世界撕碎过、然后自己把自己拼回来的灵魂。"
        ),
        next_scene="ch4_bond_02",
    ),
    Scene(
        id="ch4_bond_02",
        chapter=4,
        location="废墟村庄·地下室",
        speaker="rex",
        text=(
            "所以啊莉莉丝小姐——\n"
            "跟我们走吧。\n\n"
            "我们这个队伍的特色就是——"
        ),
        next_scene="ch4_bond_03",
    ),
    Scene(
        id="ch4_bond_03",
        chapter=4,
        location="废墟村庄·地下室",
        speaker="seraphina",
        text="闭嘴。",
        next_scene="ch4_bond_04",
    ),
    Scene(
        id="ch4_bond_04",
        chapter=4,
        location="废墟村庄·地下室",
        speaker="mira",
        text="美女很多~",
        next_scene="ch4_bond_05",
    ),
    Scene(
        id="ch4_bond_05",
        chapter=4,
        location="废墟村庄·地下室",
        speaker="luna",
        text="……？（歪头）",
        next_scene="ch4_bond_06",
    ),
    Scene(
        id="ch4_bond_06",
        chapter=4,
        location="废墟村庄·地下室",
        speaker="lilith",
        text=(
            "……你们这群人，是白痴吗？\n\n"
            "（但她的尾巴不再发抖了。）"
        ),
        next_scene="ch4_truth_01",
    ),
    Scene(
        id="ch4_truth_01",
        chapter=4,
        location="废墟村庄·夜晚",
        speaker="lilith",
        text=(
            "既然你们想知道——我告诉你们关于我父亲的事。\n\n"
            "魔王阿扎泽尔正在收集古代魔力来打破一系列封印。\n"
            "就是你们在圣城看到的那种封印——全大陆一共有七处。\n"
            "他已经破坏了五处。\n\n"
            "他说封印之下的力量可以「改写世界的法则」——\n"
            "但我觉得那只是毁灭。"
        ),
        next_scene="ch4_truth_02",
    ),
    Scene(
        id="ch4_truth_02",
        chapter=4,
        location="废墟村庄·夜晚",
        text=(
            "就在这时，露娜突然倒了下去。\n\n"
            "记忆如决堤的洪水般涌回——\n"
            "她看到了自己：穿着白色长袍，双手按在巨大的封印上——\n"
            "她是封印的守护者。\n\n"
            "然后，阿扎泽尔来了。\n"
            "他夺走了她的守护之力。她本应死去，\n"
            "但残留的守护魔力碎片让她以失忆的状态活了下来。"
        ),
        next_scene="ch4_truth_03",
    ),
    Scene(
        id="ch4_truth_03",
        chapter=4,
        location="废墟村庄·夜晚",
        speaker="luna",
        text=(
            "我……想起来了。不是全部，但是……\n\n"
            "封印……守护……一千年……\n\n"
            "阿扎泽尔，他……他叫我……\n\n"
            "（她捂住头，表情痛苦。）"
        ),
        choices=[
            Choice(
                text="所以露娜是封印的守护者……而魔王需要她剩余的力量来完成仪式？",
                next_scene="ch4_demon_attack_01",
                flags=["understood_plot"],
            ),
            Choice(
                text="不管你是谁，露娜就是露娜。你是我的同伴，我不会让任何人伤害你。",
                next_scene="ch4_demon_attack_01",
                affection={"luna": 5, "lilith": 2},
            ),
            Choice(
                text="那个魔王……就是十年前……毁了我村子的人……？",
                next_scene="ch4_demon_attack_01",
                flags=["rex_revenge_motive"],
            ),
        ],
    ),
    Scene(
        id="ch4_demon_attack_01",
        chapter=4,
        location="废墟村庄·外围",
        text=(
            "警报！\n\n"
            "远处的火光照亮了夜空——魔族军的侦察部队找到了他们。\n"
            "至少三十名魔族士兵，由一名魔族将军率领。\n\n"
            "将军认出了莉莉丝。"
        ),
        next_scene="ch4_demon_attack_02",
    ),
    Scene(
        id="ch4_demon_attack_02",
        chapter=4,
        location="废墟村庄·外围",
        text=(
            "「叛徒公主殿下~魔王陛下让我带您回去哦？\n"
            "当然，如果您不愿意的话……只能用武力了。」\n\n"
            "莉莉丝的拳头在发抖。\n"
            "不是恐惧——是愤怒和屈辱。"
        ),
        choices=[
            Choice(
                text="莉莉丝，跟我配合！你了解魔族的战斗方式，告诉我他们的弱点！",
                next_scene="ch4_demon_attack_03",
                affection={"lilith": 4},
                flags=["team_lilith"],
            ),
            Choice(
                text="所有人一起上！今晚——谁都不会被留下！",
                next_scene="ch4_demon_attack_03",
                affection={"seraphina": 2, "luna": 2, "mira": 2, "lilith": 2},
            ),
            Choice(
                text="你们先走，我来断后！快！",
                next_scene="ch4_demon_attack_03",
                affection={"seraphina": 3},
                flags=["rex_sacrifice_attempt"],
            ),
        ],
    ),
    Scene(
        id="ch4_demon_attack_03",
        chapter=4,
        location="废墟村庄·外围",
        text=(
            "激战。\n\n"
            "雷克斯释放出了真正的实力——\n"
            "金色的魔力从他体内爆发，将周围的魔族士兵一个个击退。\n"
            "赛拉菲娜的圣剑划出银色的弧光。\n"
            "露娜的古代魔法在空中编织出复杂的法阵。\n"
            "米拉的治愈结界保护着每一个人。\n"
            "莉莉丝的魔焰——现在不再是恐惧的颜色，而是战斗的赤红。\n\n"
            "魔族将军最终被击退了。\n"
            "但雷克斯身上多了好几道深深的伤口。"
        ),
        next_scene="ch4_demon_attack_04",
    ),
    Scene(
        id="ch4_demon_attack_04",
        chapter=4,
        location="废墟村庄·外围",
        text=(
            "战斗结束。\n\n"
            "赛拉菲娜沉默地用圣光治疗他的伤口，手指微微发抖。\n"
            "露娜蹲在旁边，紧紧抓着他的手，不肯松开。\n"
            "米拉一边祈祷一边流眼泪，嘴里念叨着「笨蛋笨蛋笨蛋」。\n"
            "莉莉丝站在最近的地方，背对着大家，尾巴却一直缠在雷克斯手腕上。"
        ),
        next_scene="ch4_night_01",
    ),
    Scene(
        id="ch4_night_01",
        chapter=4,
        location="营地·月光下",
        text=(
            "夜深了。其他人都睡着了——或者假装睡着了。\n\n"
            "莉莉丝独自坐在营火的边缘，尾巴卷在膝盖上。\n"
            "雷克斯缠着绷带走了过去，坐在她旁边。"
        ),
        next_scene="ch4_night_02",
    ),
    Scene(
        id="ch4_night_02",
        chapter=4,
        location="营地·月光下",
        speaker="lilith",
        text=(
            "你是白痴吗？为什么要为了我这种半魔族拼命？\n"
            "我是魔王的女儿啊？\n"
            "万一我是卧底呢？万一我在骗你们呢？\n\n"
            "你就这么轻易地相信别人……迟早会死的。"
        ),
        next_scene="ch4_night_03",
    ),
    Scene(
        id="ch4_night_03",
        chapter=4,
        location="营地·月光下",
        speaker="rex",
        text=(
            "因为你需要有人告诉你——\n"
            "你属于这里。属于我们。\n\n"
            "魔王的女儿也好，半魔族也好——\n"
            "你就是莉莉丝。\n"
            "一个明明很害怕、很孤独，\n"
            "却还是选择了正确道路的，勇敢的女孩子。\n\n"
            "而且……有犄角的女孩子确实很稀有很可爱嘛~\n"
            "我雷克斯可是鉴赏美女的专家——呃！"
        ),
        next_scene="ch4_night_04",
    ),
    Scene(
        id="ch4_night_04",
        chapter=4,
        location="营地·月光下",
        speaker="lilith",
        text=(
            "（用尾巴狠狠抽了雷克斯一下。）\n\n"
            "……笨蛋。\n"
            "明明前面说的很好的，非要在最后毁掉气氛。\n\n"
            "（但她没有站起来离开。\n"
            "月光下，她的嘴角微微上翘。\n"
            "尾巴不知不觉又缠上了雷克斯的手腕。\n"
            "这一次，她没有收回去。）"
        ),
        next_scene="ch4_end",
    ),
    Scene(
        id="ch4_end",
        chapter=4,
        location="营地·月光下",
        text=(
            "雷克斯看着篝火旁的四个同伴。\n\n"
            "赛拉菲娜抱着剑，侧身而卧，金发散在地上。\n"
            "露娜蜷缩着，怀里紧紧抱着从祭典赢来的那只猫玩偶。\n"
            "米拉握着祈祷珠，嘴角带着微笑。\n"
            "莉莉丝坐在火光的边缘，尾巴还缠在他手腕上。\n\n"
            "他想起了远方的艾莲娜。\n\n"
            "「五个……不对，五个美女围绕着我……\n"
            "这不是梦想成真吗？」\n\n"
            "他咧嘴一笑。但笑容很快黯淡下来。\n\n"
            "「可是……为什么我觉得……\n"
            "如果失去了她们任何一个……\n"
            "我会比十年前还要害怕。」\n\n"
            "一阵黑风吹过。\n"
            "远方的火山口泛起了暗红色的光芒。\n"
            "最终的战斗，近了。"
        ),
        next_scene="ch5_return_01",
    ),
]

register(*SCENES)
