"""第二章：低语之森"""
from .common import Scene, Choice, register

SCENES = [
    Scene(
        id="ch2_forest_01",
        chapter=2,
        location="低语之森·入口",
        text=(
            "低语之森。\n\n"
            "古老的巨树遮天蔽日，阳光只能从缝隙中洒下斑驳的光斑。\n"
            "空气中弥漫着潮湿的泥土气息和一种说不出的……沉重感。\n\n"
            "树叶在无风的空气中轻轻颤动，仿佛在低声诉说着什么。"
        ),
        next_scene="ch2_forest_02",
    ),
    Scene(
        id="ch2_forest_02",
        chapter=2,
        location="低语之森·入口",
        speaker="rex",
        text=(
            "嘶——这森林气氛也太阴沉了。\n"
            "赛拉菲娜，你说这里面会不会有精灵？\n"
            "我听说森精灵都穿着树叶编的衣服，若隐若现的那种——"
        ),
        next_scene="ch2_forest_03",
    ),
    Scene(
        id="ch2_forest_03",
        chapter=2,
        location="低语之森·入口",
        speaker="seraphina",
        text=(
            "闭嘴。集中注意力。\n\n"
            "……你闻到了吗？空气里有一种腐蚀性魔力的气息。\n"
            "这种黑暗魔力的残留……和十年前毁灭了好几个村庄的那种一模一样。"
        ),
        next_scene="ch2_dark_01",
    ),
    Scene(
        id="ch2_dark_01",
        chapter=2,
        location="低语之森·古树之间",
        text="听到「十年前」和「毁灭村庄」这几个字，雷克斯的表情变了。\n那种变化转瞬即逝，但确实存在过。",
        choices=[
            Choice(
                text="（攥紧拳头，沉默不语。指节因为用力而发白。）",
                next_scene="ch2_dark_02",
                affection={"seraphina": 2},
                flags=["rex_past_hint"],
            ),
            Choice(
                text="十年前……吗。那时候我还在到处流浪呢。没什么印象了。",
                next_scene="ch2_dark_02",
                flags=["rex_past_hint"],
            ),
            Choice(
                text="黑暗魔法？听起来很危险啊。要不我们先回去叫增援？（才不是害怕呢）",
                next_scene="ch2_dark_02",
            ),
        ],
    ),
    Scene(
        id="ch2_dark_02",
        chapter=2,
        location="低语之森·古树之间",
        speaker="seraphina",
        text=(
            "……继续前进。\n\n"
            "（她看了雷克斯一眼，欲言又止，最终还是没有追问。）"
        ),
        next_scene="ch2_luna_01",
    ),
    Scene(
        id="ch2_luna_01",
        chapter=2,
        location="低语之森·月光空地",
        text=(
            "他们在森林深处发现了一片空地。\n\n"
            "月光奇迹般地穿透了树冠，照在空地中央——\n"
            "一个银发少女倒在枯萎的花丛中，浑身散发着微弱而不稳定的魔力波动。\n\n"
            "她的耳朵是尖的。精灵。"
        ),
        next_scene="ch2_luna_02",
    ),
    Scene(
        id="ch2_luna_02",
        chapter=2,
        location="低语之森·月光空地",
        speaker="rex",
        text=(
            "银发精灵美少女！！！\n"
            "今天运气太好了吧？！虽然是来调查黑暗魔力的，但是\n"
            "天上掉下来个精灵妹——啊好痛！"
        ),
        next_scene="ch2_luna_03",
    ),
    Scene(
        id="ch2_luna_03",
        chapter=2,
        location="低语之森·月光空地",
        speaker="seraphina",
        text="（一拳锤在雷克斯头上）\n\n先看看她有没有受伤。你是来执行任务的，不是来搭讪的。",
        next_scene="ch2_luna_04",
    ),
    Scene(
        id="ch2_luna_04",
        chapter=2,
        location="低语之森·月光空地",
        text=(
            "精灵少女缓缓睁开了眼睛。\n\n"
            "那是一双不可思议的紫色眼眸——像是融化的紫水晶，\n"
            "既清澈又深邃，却没有任何感情的波动。\n\n"
            "她茫然地看着面前的两个人。"
        ),
        next_scene="ch2_luna_05",
    ),
    Scene(
        id="ch2_luna_05",
        chapter=2,
        location="低语之森·月光空地",
        speaker="luna",
        text=(
            "……你们是谁。\n\n"
            "我是……我叫……露娜。\n"
            "其他的……什么都想不起来了。"
        ),
        next_scene="ch2_luna_06",
    ),
    Scene(
        id="ch2_luna_06",
        chapter=2,
        location="低语之森·月光空地",
        speaker="luna",
        text=(
            "（露娜突然抓住了雷克斯的手臂，把脸贴了上去。）\n\n"
            "……你的魔力。好温暖。\n"
            "像是……太阳。不，比太阳更……\n\n"
            "（她毫无表情地说着，却死死抱住雷克斯的手不放。）"
        ),
        choices=[
            Choice(
                text="当然温暖了！因为我体内燃烧着对美女永不熄灭的热情之火！",
                next_scene="ch2_explore_01",
                affection={"luna": 1, "seraphina": -1},
            ),
            Choice(
                text="（认真地检查露娜的魔力状况）你的魔力核心受损了……而且损伤很深。需要时间慢慢恢复。",
                next_scene="ch2_explore_01",
                affection={"luna": 3},
                flags=["rex_magic_knowledge"],
            ),
            Choice(
                text="赛拉菲娜你别那个眼神看我！是她自己抱上来的！我是无辜的！",
                next_scene="ch2_explore_01",
                affection={"seraphina": 1},
            ),
        ],
    ),
    Scene(
        id="ch2_explore_01",
        chapter=2,
        location="低语之森·深处",
        text=(
            "他们决定带上露娜继续深入调查。\n\n"
            "露娜虽然失去了记忆，但她能感应到黑暗魔力的流向。\n"
            "她始终寸步不离地跟着雷克斯，面无表情地牵着他的衣角。\n\n"
            "赛拉菲娜走在后面，不知道为什么觉得很烦躁。"
        ),
        next_scene="ch2_explore_02",
    ),
    Scene(
        id="ch2_explore_02",
        chapter=2,
        location="低语之森·营地",
        text=(
            "夜幕降临。三人在一棵巨大古树下扎营。\n\n"
            "露娜独自坐在离篝火稍远的地方，仰头看着从树缝中漏下的月光。\n"
            "她的银发在月光下几乎发出淡淡的荧光。\n\n"
            "雷克斯端着一碗热汤走了过去。"
        ),
        next_scene="ch2_explore_03",
    ),
    Scene(
        id="ch2_explore_03",
        chapter=2,
        location="低语之森·营地",
        speaker="luna",
        text=(
            "……为什么对我好？\n\n"
            "你想要什么？\n\n"
            "（她接过汤碗，面无表情地看着雷克斯。\n"
            "那双紫色的眼睛里没有任何防备——\n"
            "不是因为信任，而是因为她似乎根本不知道'防备'是什么。）"
        ),
        choices=[
            Choice(
                text="因为你是美女啊~对美女好不需要理由！这是雷克斯哲学的第一条！",
                next_scene="ch2_ruins_01",
                affection={"luna": 1},
            ),
            Choice(
                text="因为你一个人太孤独了。那种感觉……我知道。",
                next_scene="ch2_explore_04",
                affection={"luna": 5, "seraphina": 1},
                flags=["luna_bond"],
            ),
            Choice(
                text="说实话，你抱着我的时候挺舒服的。软软的。",
                next_scene="ch2_ruins_01",
                affection={"luna": 2},
            ),
        ],
    ),
    Scene(
        id="ch2_explore_04",
        chapter=2,
        location="低语之森·营地",
        speaker="luna",
        text=(
            "……孤独。\n\n"
            "（她低头看着汤碗里自己的倒影。）\n\n"
            "这个词……好像……我应该很熟悉。\n"
            "但是想不起来了。只剩下……胸口这里，一种空荡荡的感觉。\n\n"
            "（不远处，赛拉菲娜假装在擦剑，但耳朵竖得笔直。）"
        ),
        next_scene="ch2_ruins_01",
    ),
    Scene(
        id="ch2_ruins_01",
        chapter=2,
        location="低语之森·古代遗迹",
        text=(
            "第二天，他们发现了一座被藤蔓覆盖的古代遗迹。\n\n"
            "石壁上刻满了古老的符文，空气中的黑暗魔力在这里格外浓郁。\n"
            "露娜突然停下脚步，双手捂住了头。"
        ),
        next_scene="ch2_ruins_02",
    ),
    Scene(
        id="ch2_ruins_02",
        chapter=2,
        location="低语之森·古代遗迹",
        speaker="luna",
        text=(
            "呃……啊啊啊啊——！！\n\n"
            "（碎片化的记忆如潮水般涌来——\n"
            "火焰，毁灭，一个巨大的黑色身影，\n"
            "然后是……一只手，伸向她——）\n\n"
            "（露娜的身体爆发出一股强大的黑暗魔力冲击波。）"
        ),
        choices=[
            Choice(
                text="露娜！冷静下来！（不顾危险冲向她）",
                next_scene="ch2_ruins_03",
                affection={"luna": 3},
                flags=["saved_luna"],
            ),
            Choice(
                text="赛拉菲娜，用圣光压制她的魔力波动！",
                next_scene="ch2_ruins_03",
                affection={"seraphina": 2, "luna": 1},
            ),
            Choice(
                text="（用自己的魔力包裹住露娜暴走的魔力，像茧一样裹住她）",
                next_scene="ch2_ruins_03",
                affection={"luna": 4},
                flags=["saved_luna"],
                condition="rex_magic_knowledge",
            ),
        ],
    ),
    Scene(
        id="ch2_ruins_03",
        chapter=2,
        location="低语之森·古代遗迹",
        text=(
            "魔力风暴渐渐平息。\n\n"
            "露娜瘫倒在雷克斯怀里，呼吸急促。\n"
            "她的眼中有泪光闪过——这是她第一次表现出明显的情感波动。"
        ),
        next_scene="ch2_ruins_04",
    ),
    Scene(
        id="ch2_ruins_04",
        chapter=2,
        location="低语之森·古代遗迹",
        speaker="luna",
        text=(
            "阿扎泽尔……\n\n"
            "那个名字……好熟悉……好可怕……\n\n"
            "但同时……又好悲伤。为什么……我会为一个可怕的名字感到悲伤？"
        ),
        next_scene="ch2_reveal_01",
    ),
    Scene(
        id="ch2_reveal_01",
        chapter=2,
        location="低语之森·古代遗迹",
        speaker="seraphina",
        text=(
            "阿扎泽尔——那是魔王的名字。\n\n"
            "……这个精灵知道魔王的名字？这不正常。\n"
            "雷克斯，我认为我们应该把她送回圣骑士团接受审问——"
        ),
        next_scene="ch2_reveal_02",
    ),
    Scene(
        id="ch2_reveal_02",
        chapter=2,
        location="低语之森·古代遗迹",
        text="赛拉菲娜的手放在了剑柄上。\n露娜缩在雷克斯身后，无助地抓着他的衣角。",
        choices=[
            Choice(
                text="她只是个失去记忆的女孩。你看她的眼神——那不是敌人的眼神。",
                next_scene="ch2_night_01",
                affection={"luna": 4, "seraphina": -1},
                flags=["protect_luna"],
            ),
            Choice(
                text="先调查清楚再说。如果她真的危险，到时候我来负责。",
                next_scene="ch2_night_01",
                affection={"luna": 2, "seraphina": 2},
                flags=["protect_luna"],
            ),
            Choice(
                text="你说得对，我们应该小心。但是……我不想伤害她。",
                next_scene="ch2_night_01",
                affection={"seraphina": 3, "luna": 1},
                flags=["protect_luna"],
            ),
        ],
    ),
    Scene(
        id="ch2_night_01",
        chapter=2,
        location="营地·星空下",
        text=(
            "入夜。\n\n"
            "雷克斯很快就睡着了——或者说，看起来睡着了。\n\n"
            "露娜悄悄坐到了他身边。\n"
            "月光下，她看着雷克斯的睡脸，轻轻地伸出手，\n"
            "触碰了一下他的脸颊。"
        ),
        next_scene="ch2_night_02",
    ),
    Scene(
        id="ch2_night_02",
        chapter=2,
        location="营地·星空下",
        speaker="luna",
        text=(
            "温暖……\n\n"
            "第一次……感觉到这种东西。\n\n"
            "（她把脸贴近雷克斯，像一只小动物在汲取温度。）\n\n"
            "不要消失……好不好？"
        ),
        next_scene="ch2_night_03",
    ),
    Scene(
        id="ch2_night_03",
        chapter=2,
        location="营地·星空下",
        text=(
            "不远处的树影里，赛拉菲娜靠着树干，看着这一幕。\n\n"
            "她想起了自己的弟弟——也总是像个傻瓜一样，\n"
            "明明自己都伤痕累累了，还要去温暖别人。\n\n"
            "一滴眼泪划过她的脸颊。\n"
            "她用手背快速擦掉，像是在否认它的存在。"
        ),
        next_scene="ch2_end",
    ),
    Scene(
        id="ch2_end",
        chapter=2,
        location="低语之森·出口",
        text=(
            "破晓时分。\n\n"
            "森林的尽头出现在眼前。\n"
            "远方，圣城塞莱斯蒂亚的尖塔在朝阳中闪耀着金色的光芒。\n\n"
            "露娜第一次露出了笑容——淡淡的，几乎看不到的弧度。\n"
            "但就像冰雪消融的第一滴水，带着生命的气息。\n\n"
            "雷克斯看到了，咧嘴一笑：\n"
            "「看吧，我就说跟着我会有好事发生！」\n\n"
            "但他的眼睛望向远方的圣城，露出了谁都没见过的认真表情。\n"
            "那里……会有什么在等着他们呢？"
        ),
        next_scene="ch3_city_01",
    ),
]

register(*SCENES)
